<?php
/**
 * MLM System
 *
 * @author    Adrian Wądrzyk <adrian.wadrzyk@gmail.com>
 * @copyright 2012 Adrian Wądrzyk. All rights reserved.
 */
?>

<div class="info">
	<h4 class="settlements">Rozliczenia</h4>
	<?php echo $this->relatedLinks(); ?>
	<?php echo $this->filter->render(); ?>
	<ul class="list-options list-style-none">
		<li class="add"><a href="/settlements/settle">Rozlicz pracowników</a>
	</ul>
</div>
<?php echo $this->flashMessenger(); ?>
<?php echo $this->partial("paginator.phtml", $this->paginator->getPages()); ?>

<?php if ($this->paginator->getTotalItemCount()) : ?>
	<table class="table">
		<thead>
			<tr>
				<th class="id"><?php echo $this->sortLink("settlement_id", "Id"); ?></th>
				<th><?php echo $this->sortLink(array("lastname", "firstname"), "Pracownik", "employees"); ?></th>
				<th><?php echo $this->sortLink("email", "Email", "employees"); ?></th>
				<th><?php echo $this->sortLink("create_date", "Data utworzenia"); ?></th>
				<th><?php echo $this->sortLink("total", "Kwota"); ?></th>
				<th><?php echo $this->sortLink("tax", "Podatek"); ?></th>
				<th class="actions">Akcje</th>
			</tr>
		</thead>
		<tbody>
			<?php echo $this->partialLoop("settlements/partials/list-item.phtml", $this->paginator); ?>
		</tbody>
	</table>
<?php endif; ?>