<?php
/**
 * MLM System
 *
 * @author    Adrian Wądrzyk <adrian.wadrzyk@gmail.com>
 * @copyright 2012 Adrian Wądrzyk. All rights reserved.
 */
?>

<div class="info">
	<h4 class="applications">Wnioski</h4>
	<?php echo $this->relatedLinks(); ?>
	<ul class="list-options list-style-none">
		<li class="back"><a href="/applications">Wróć do listy</a>
		<li class="add"><a href="/applications/add">Dodaj wniosek</a>
		<li class="delete"><a href="<?php echo $this->url(array("action" => "delete"));?>">Usuń wniosek</a>
	</ul>
</div>
<?php echo $this->flashMessenger(); ?>
<?php echo $this->form; ?>
<script type="text/javascript">
	$(document).ready(function() {
		JsonAction.initialize("#partner", "id", "#product");
	});
</script>
