<?php
/**
 * MLM System
 *
 * @author    Adrian Wądrzyk <adrian.wadrzyk@gmail.com>
 * @copyright 2012 Adrian Wądrzyk. All rights reserved.
 */
?>

<div class="info">
	<h4 class="applications">Wnioski</h4>
	<?php echo $this->relatedLinks(); ?>
	<?php echo $this->filter->render(); ?>
	<ul class="list-options list-style-none">
		<li class="add"><a href="/applications/add">Dodaj wniosek</a>
	</ul>
</div>
<?php echo $this->flashMessenger(); ?>
<?php echo $this->partial("paginator.phtml", $this->paginator->getPages()); ?>

<?php if ($this->paginator->getTotalItemCount()) : ?>
	<table class="table">
		<thead>
			<tr>
				<th class="id"><?php echo $this->sortLink("application_id", "Id"); ?></th>
				<th><?php echo $this->sortLink(array("lastname", "firstname"), "Klient", "customers"); ?></th>
				<th><?php echo $this->sortLink(array("lastname", "firstname"), "Pracownik", "employees"); ?></th>
				<th><?php echo $this->sortLink("name", "Produkt", "products"); ?></th>
				<th><?php echo $this->sortLink("name", "Rozliczenie", "setllement_types"); ?></th>
				<th><?php echo $this->sortLink("create_date", "Data dodania"); ?></th>
				<th><?php echo $this->sortLink("name", "Waluta", "currency"); ?></th>
				<th><?php echo $this->sortLink("name", "Status", "application_statuses"); ?></th>
				<th class="actions">Akcje</th>
			</tr>
		</thead>
		<tbody>
			<?php echo $this->partialLoop("applications/partials/list-item.phtml", $this->paginator); ?>
		</tbody>
	</table>
<?php endif; ?>