<?php
/**
 * MLM System
 *
 * @author    Adrian Wądrzyk <adrian.wadrzyk@gmail.com>
 * @copyright 2012 Adrian Wądrzyk. All rights reserved.
 */
?>

<div class="info">
	<h4 class="customers">Klienci</h4>
	<?php echo $this->relatedLinks(); ?>
	<?php echo $this->filter->render(); ?>
	<ul class="list-options list-style-none">
		<li class="add"><a href="/customers/add">Dodaj klienta</a>
	</ul>
</div>
<?php echo $this->flashMessenger(); ?>
<?php echo $this->partial("paginator.phtml", $this->paginator->getPages()); ?>

<?php if ($this->paginator->getTotalItemCount()) : ?>
	<table class="table">
		<thead>
			<tr>
				<th class="id"><?php echo $this->sortLink("customer_id", "Id"); ?></th>
				<th><?php echo $this->sortLink(array("lastname", "firstname"), "Nazwisko Imię"); ?></th>
				<th><?php echo $this->sortLink("cell_phone_number", "Telefon"); ?></th>
				<th><?php echo $this->sortLink("email", "Email"); ?></th>
				<th><?php echo $this->sortLink(array("lastname", "firstname"), "Doradca", "employees"); ?></th>
				<th><?php echo $this->sortLink("city", "Miasto", "customer_addresses"); ?></th>
				<th><?php echo $this->sortLink("create_date", "Data dodania"); ?></th>
				<th class="activity"><?php echo $this->sortLink("active", "Aktywność"); ?></th>
				<th class="actions">Akcje</th>
			</tr>
		</thead>
		<tbody>
			<?php echo $this->partialLoop("customers/partials/list-item.phtml", $this->paginator); ?>
		</tbody>
	</table>
<?php endif; ?>