<?php
/**
 * MLM System
 *
 * @author    Adrian Wądrzyk <adrian.wadrzyk@gmail.com>
 * @copyright 2012 Adrian Wądrzyk. All rights reserved.
 */
?>

<div class="info">
	<h4 class="news">News-y</h4>
	<?php echo $this->relatedLinks(); ?>
	<ul class="list-options list-style-none">
		<li class="back"><a href="/news">Wróć do listy</a>
		<li class="add"><a href="/news/add">Dodaj news</a>
		<li class="delete"><a href="<?php echo $this->url(array("action" => "delete"));?>">Usuń news</a>
	</ul>
</div>
<?php echo $this->flashMessenger(); ?>
<?php echo $this->form; ?>

<script type="text/javascript">
    FormAjax.documentAjaxUpload();
</script>