<?php
/**
 * MLM System
 *
 * @author    Adrian Wądrzyk <adrian.wadrzyk@gmail.com>
 * @copyright 2012 Adrian Wądrzyk. All rights reserved.
 */
?>

<div class="info">
	<h4 class="news">News-y</h4>
	<?php echo $this->relatedLinks(); ?>
	<ul class="list-options list-style-none">
		<li class="add"><a href="/news/add">Dodaj news</a>
	</ul>
</div>
<?php echo $this->flashMessenger(); ?>
<?php echo $this->partial("paginator.phtml", $this->paginator->getPages()); ?>

<?php if ($this->paginator->getTotalItemCount()) : ?>
	<table class="table">
		<thead>
			<tr>
				<th class="id"><?php echo $this->sortLink("news_id", "Id"); ?></th>
				<th><?php echo $this->sortLink("name", "Nazwa"); ?></th>
				<th>Grupy</th>
				<th class="activity"><?php echo $this->sortLink("active", "Aktywność"); ?></th>
				<th class="actions">Akcje</th>
			</tr>
		</thead>
		<tbody>
			<?php echo $this->partialLoop("news/partials/list-item.phtml", $this->paginator); ?>
		</tbody>
	</table>
<?php endif; ?>