<?php
/**
 * MLM System
 *
 * @author    Adrian Wądrzyk <adrian.wadrzyk@gmail.com>
 * @copyright 2012 Adrian Wądrzyk. All rights reserved.
 */
?>

<?php if ($this->model->customers->count() > 0) : ?>
	<table class="table">
		<thead>
			<tr>
				<th class="id">Id</th>
				<th>Klient</th>
				<th>Email</th>
				<th>Status</th>
				<th>Groupa</th>
				<th>Aktywność</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->model->customers as $customer) : ?>
				<tr>
					<td><?php echo $customer->getIdentifier(); ?></td>
					<td><?php echo $customer->lastname . " " . $customer->firstname; ?></td>
					<td><?php echo $customer->email; ?></td>
					<td><?php echo $customer->status->name; ?></td>
					<td><?php echo $customer->group->name; ?></td>
					<td class="activity"><?php echo $customer->active; ?></td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
<?php else :?>
	<?php echo $this->noResults(); ?>
<?php endif; ?>