<?php
/**
 * MLM System
 *
 * @author    Adrian Wądrzyk <adrian.wadrzyk@gmail.com>
 * @copyright 2012 Adrian Wądrzyk. All rights reserved.
 */
?>

<div class="info">
	<h4 class="employees">Typy umów</h4>
	<?php echo $this->relatedLinks(); ?>
	<ul class="list-options list-style-none">
		<li class="back"><a href="/agreement-types">Wroć do listy</a>
		<li class="add"><a href="/agreement-types/add">Dodaj typ umowy</a>
		<li class="delete"><a href="<?php echo $this->url(array("action" => "delete"));?>">Usuń typ umowy</a>
	</ul>
</div>
<?php echo $this->flashMessenger(); ?>
<?php echo $this->form; ?>