<?php
/**
 * MLM System
 *
 * @author    Adrian Wądrzyk <adrian.wadrzyk@gmail.com>
 * @copyright 2012 Adrian Wądrzyk. All rights reserved.
 */
?>

<tr class="color-<?php echo ($this->partialCounter % 2); ?>">
	<td><?php echo $this->model->identifier; ?></td>
	<td><?php echo $this->model->name; ?></td>
	<td>
		<?php if ($this->model->contactPerson) : ?>
			<?php echo $this->model->contactPerson->lastname . ' ' . $this->model->contactPerson->firstname; ?>
		<?php endif; ?>
	</td>
	<td>
		<?php if ($this->model->contactPerson) : ?>
			<?php echo $this->model->contactPerson->email; ?>
		<?php endif; ?>
	</td>
	<td>
		<?php if ($this->model->contactPerson) : ?>
			<?php echo $this->model->contactPerson->city; ?>
		<?php endif; ?>
	</td>
	<td>
		<?php if ($this->model->contactPerson) : ?>
			<?php echo $this->model->contactPerson->phoneNumber; ?>
		<?php endif; ?>
	</td>
	<td class="activity"><?php echo $this->model->active; ?></td>
	<td>
		<ul class="list-style-none actions">
			<li class="edit"><a href="/partners/edit/<?php echo $this->model->identifier; ?>" alt="edytuj" title="edytuj"></a></li>
			<li class="delete"><a href="/partners/delete/<?php echo $this->model->identifier; ?>" alt="usuń" title="usuń"></a></li>
		</ul>
	</td>
</tr>
