<?php
/**
 * MLM System
 *
 * @author    Adrian Wądrzyk <adrian.wadrzyk@gmail.com>
 * @copyright 2012 Adrian Wądrzyk. All rights reserved.
 */
?>

<?php if ($this->model->getIdentifier()) : ?>
	<ul class="list-options list-style-none ajax-options">
		<li class="add"><a href="/layer/customer-credits/add/<?php echo $this->model->getIdentifier(); ?>">Dodaj kredyt</a></li>
	</ul>
<?php endif; ?>
<?php if ($this->model->credits->count() > 0) : ?>
	<table class="table">
		<thead>
			<tr>
				<th class="id">Id</th>
				<th>Typ</th>
				<th>Bank</th>
				<th>Marża</th>
				<th>RRSO</th>
				<th>Rata</th>
				<th>Saldo</th>
				<th>Na dzień</th>
				<th>Akcje</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->model->credits as $credit) : ?>
				<tr>
					<td><?php echo $credit->getIdentifier(); ?></td>
					<td><?php echo $credit->type->name; ?></td>
					<td><?php echo $credit->bank; ?></td>
					<td><?php echo $credit->margin; ?></td>
					<td><?php echo $credit->rrso; ?></td>
					<td><?php echo $credit->installment; ?></td>
					<td><?php echo $credit->balance; ?></td>
					<td><?php echo $credit->balanceDate; ?></td>
					<td>
						<ul class="list-style-none actions ajax-options">
							<li class="edit">
								<a href="/layer/customer-credits/edit/<?php echo $credit->getIdentifier() . "/" . $this->model->getIdentifier(); ?>" alt="edytuj" title="edytuj"></a>
							</li>
							<li class="delete">
								<a href="/layer/customer-credits/delete/<?php echo $credit->getIdentifier() . "/" . $this->model->getIdentifier(); ?>" alt="usuń" title="usuń"></a>
							</li>
						</ul>
					</td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
<?php else :?>
	<?php echo $this->noResults(); ?>
<?php endif; ?>