<?php
/**
 * MLM System
 *
 * @author    Adrian Wądrzyk <adrian.wadrzyk@gmail.com>
 * @copyright 2012 Adrian Wądrzyk. All rights reserved.
 */
?>

<tr class="color-<?php echo ($this->partialCounter % 2); ?>">
	<td><?php echo $this->model->identifier; ?></td>
	<td><?php echo $this->model->lastname . ' ' . $this->model->firstname; ?></td>
	<td><?php echo $this->model->cellPhoneNumber; ?></td>
	<td><?php echo $this->model->email; ?></td>
	<td>
		<?php if ($this->model->employee) : ?>
			<?php echo $this->model->employee->lastname . ' ' . $this->model->employee->firstname; ?>
		<?php endif; ?>
	</td>
	<td>
		<?php if ($this->model->addresses->count()) : ?>
			<?php echo $this->model->addresses->current()->city; ?>
		<?php endif; ?>
	</td>
	<td><?php echo $this->model->createDate; ?></td>
	<td class="activity"><?php echo $this->model->active; ?></td>
	<td>
		<ul class="list-style-none actions">
			<li class="edit"><a href="/customers/edit/<?php echo $this->model->identifier; ?>" alt="edytuj" title="edytuj"></a></li>
			<li class="delete"><a href="/customers/delete/<?php echo $this->model->identifier; ?>" alt="usuń" title="usuń"></a></li>
		</ul>
	</td>
</tr>
