<?php
/**
 * MLM System
 *
 * @author    Adrian Wądrzyk <adrian.wadrzyk@gmail.com>
 * @copyright 2012 Adrian Wądrzyk. All rights reserved.
 */
?>

<?php if ($this->model->products->count() > 0) : ?>
	<table class="table">
		<thead>
			<tr>
				<th class="id">Id</th>
				<th>Partner</th>
				<th>Nazwa</th>
				<th>Osoba kontaktowa</th>
				<th>Typ</th>
				<th>Aktywność</th>
				<th>Wniosek</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->model->products as $product) : ?>
				<tr>
					<td><?php echo $product->getIdentifier(); ?></td>
					<td><?php echo $product->partner->name; ?></td>
					<td><?php echo $product->name; ?></td>
					<td><?php echo $product->contactPerson->lastname . " " . $product->contactPerson->firstname; ?></td>
					<td><?php echo $product->type->name; ?></td>
					<td class="activity"><?php echo $product->active; ?></td>
					<td>
					    <ul class="list-style-none actions ajax-options">
							<li class="edit">
								<a href="/layer/customer-products/edit/<?php echo $product->getIdentifier() . "/" . $this->model->getIdentifier(); ?>" alt="edytuj" title="edytuj"></a>
							</li>
						</ul>
					</td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
<?php else :?>
	<?php echo $this->noResults(); ?>
<?php endif; ?>