<?php
/**
 * MLM System
 *
 * @author    Adrian Wądrzyk <adrian.wadrzyk@gmail.com>
 * @copyright 2012 Adrian Wądrzyk. All rights reserved.
 */
?>

<?php if ($this->model->getIdentifier()) : ?>
	<ul class="list-options list-style-none ajax-options">
		<li class="add"><a href="/layer/customer-renouncements/add/<?php echo $this->model->getIdentifier(); ?>">Dodaj odstąpienie</a></li>
	</ul>
<?php endif; ?>
<?php if ($this->model->renouncements->count() > 0) : ?>
	<table class="table">
		<thead>
			<tr>
				<th class="id">Id</th>
				<th>Numer polisy</th>
				<th>Data zawarcia polisy</th>
				<th>Data wysłania dokumentu</th>
				<th>Akcje</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->model->renouncements as $renouncement) : ?>
				<tr>
					<td><?php echo $renouncement->getIdentifier(); ?></td>
					<td><?php echo $renouncement->policyNumber; ?></td>
					<td><?php echo $renouncement->policyCreateDate; ?></td>
					<td><?php echo $renouncement->documentSendDate; ?></td>
					<td>
						<ul class="list-style-none actions ajax-options">
							<li class="edit">
								<a href="/layer/customer-renouncements/edit/<?php echo $renouncement->getIdentifier() . "/" . $this->model->getIdentifier(); ?>" alt="edytuj" title="edytuj"></a>
							</li>
							<li class="delete">
								<a href="/layer/customer-renouncements/delete/<?php echo $renouncement->getIdentifier() . "/" . $this->model->getIdentifier(); ?>" alt="usuń" title="usuń"></a>
							</li>
						</ul>
					</td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
<?php else :?>
	<?php echo $this->noResults(); ?>
<?php endif; ?>