<?php
/**
 * MLM System
 *
 * @author    Adrian Wądrzyk <adrian.wadrzyk@gmail.com>
 * @copyright 2012 Adrian Wądrzyk. All rights reserved.
 */
?>

<tr class="color-<?php echo ($this->partialCounter % 2); ?>">
	<td><?php echo $this->model->identifier; ?></td>
	<td><?php echo $this->model->name; ?></td>
	<td class="activity"><?php echo $this->model->active; ?></td>
	<td>
		<ul class="list-style-none actions">
			<li class="edit"><a href="/product-types/edit/<?php echo $this->model->identifier; ?>" alt="edytuj" title="edytuj"></a></li>
			<li class="delete"><a href="/product-types/delete/<?php echo $this->model->identifier; ?>" alt="usuń" title="usuń"></a></li>
		</ul>
	</td>
</tr>
